---
- hosts: all
  become: true

  vars_files:
    - vars/main.yml
    - vars/app.yml

  handlers:
    - include: handlers/common.yml
    - include: handlers/services.yml

  tasks:
    - include: tasks/app/user.yml
    - include: tasks/app/config.yml
    - include: tasks/app/postgresql.yml
    - include: tasks/app/nginx.yml
    - include: tasks/app/systemd.yml
