---
- hosts: all
  become: true

  vars_files:
    - vars/server.yml
    - vars/app.yml

  handlers:
    - include: handlers/common.yml
    - include: handlers/services.yml

  tasks:
    - include: tasks/app/user.yml
    - include: tasks/app/db.yml
