---
- hosts: rails
  become: true

  vars_files:
    - vars/main.yml

  handlers:
    - include: handlers/main.yml

  tasks:
    - include: tasks/server/update.yml
    - include: tasks/server/basic.yml
    - include: tasks/server/locale.yml
    - include: tasks/server/dependencies.yml
    - include: tasks/server/postgresql.yml
    - include: tasks/server/ruby.yml
    - include: tasks/server/nginx.yml
