---
- hosts: all
  become: true

  vars_files:
    - vars/server.yml

  handlers:
    - include: handlers/common.yml
    - include: handlers/services.yml

  tasks:
    - include: tasks/server/update.yml
    - include: tasks/server/locale.yml
    - include: tasks/server/dependencies.yml
    - include: tasks/server/ruby.yml
    - include: tasks/server/nginx.yml
