- name: set secret_key_base
  shell: 'ruby -e "require \"securerandom\"; puts SecureRandom.hex(64)"'
  register: secret_key_base_result

- set_fact: secret_key_base={{ secret_key_base_result.stdout }}
