---
- name: main hostname
  lineinfile:
    dest: /etc/postfix/main.cf
    line: "myhostname = {{ domain }}"
    regexp: "^myhostname(.*)$"
  notify: restart mail service

- name: setup aliases
  lineinfile:
    dest: /etc/aliases
    line: "{{ item.name }}: {{ item.user }}"
    create: yes
  with_items:
    - { name: "hello", user: "{{ user }}" }
    - { name: "admin", user: "root" }
  notify: restart mail service
