---
- name: setup database
  become_user: postgres
  postgresql_db: name="{{ db_name }}"

- name: setup user
  become_user: postgres
  postgresql_user: name="{{ db_user }}"

- name: grant user privileges on database
  become_user: postgres
  postgresql_privs:
    database: "{{ db_name }}"
    privs: ALL
    role:  "{{ db_user }}"
    type: database

- name: enable extensions
  become_user: postgres
  postgresql_ext: name={{ item }} db={{ db_name }}
  with_items:
    - cube
    - earthdistance
    - postgis

- name: allow peer access to user
  lineinfile:
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    insertafter: 'TYPE.*DATABASE.*USER.*ADDRESS.*METHOD'
    line: "local {{ db_name }} {{ db_user }} peer"
  notify: restart postgresql
