---
- name: creates user
  user: name="{{ user }}" shell=/bin/bash

- name: create user application directory
  become_user: "{{ user }}"
  file: path="/home/{{ user }}/app" state=directory

- name: Set up authorized_keys
  authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', key_file) }}"

- name: user environment
  blockinfile:
    dest: "/home/{{ user }}/.bashrc"
    content: |
      export RAILS_ENV=production

- name: make sudoer
  lineinfile:
    dest: "/etc/sudoers"
    line: "{{ user }} ALL=(ALL) NOPASSWD:ALL"
    validate: "visudo -cf %s"
