---
- name: install build packages
  apt: name=build-essential

- name: install git
  apt: name=git

- name: install javascript runtime
  apt: name=nodejs

- name: install imagemagick
  apt: name={{ item }}
  with_items:
    - imagemagick
    - libmagickwand-dev

- name: install redis
  apt: name=redis-server

- name: install postgresql prerequisites
  apt: name=python-psycopg2
