---
- name: install build packages
  apt: name=build-essential

- name: install git
  apt: name=git

- name: install javascript runtime
  apt: name={{ item }}
  with_items:
    - nodejs
    - nodejs-legacy
    - npm

- name: install imagemagick
  apt: name={{ item }}
  with_items:
    - imagemagick
    - libmagickwand-dev

- name: install redis
  apt: name=redis-server

- name: install postgresql prerequisites
  apt: name=python-psycopg2

- name: install mail
  apt: name={{ item }}
  with_items:
    - postfix
    - mailutils
