---
- name: install postgresql ppa key
  apt_key:
    url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'

- name: add postgresql ppa
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ubuntu_version }}-pgdg main"
  notify: apt update

- name: install postgresql
  apt: name={{ item }}
  with_items:
    - postgresql
    - postgresql-server-dev-all
    - postgresql-contrib
