---
- name: add postgresql ppa
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ubuntu }}-pgdg main"

- name: install postgresql ppa key
  apt_key:
    url: 'https://www.postgresql.org/media/keys/ACCC4CF8.asc'

- name: update apt cache
  apt: update_cache=yes

- name: install prerequisites
  apt: name=python-psycopg2

- name: install postgresql
  apt: name={{ item }}
  with_items:
    - "postgresql-{{ postgresql_version }}"
    - "postgresql-server-dev-{{ postgresql_version }}"
    - "postgresql-contrib-{{ postgresql_version }}"
