---
- name: apt update
  apt: update_cache=yes

- name: restart nginx
  service: name=nginx state=restarted

- name: restart postgresql
  service: name=posgresql state=restarted

- name: load mail mappings
  command: postmap /etc/postfix/virtual
  notify: restart mail service

- name: restart mail service
  service: name=postfix state=restarted
